---
# Apply latest Ruby style guide and newly introduced cops
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Include:
    - Gemfile
    - Rakefile
    - '**/*.rb'
  Exclude:
    - _snippets/*
    - 'app/infrastructure/git/repostore/**/*'

# ignore block length where unavoidable (e.g., framework requires it)
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - app/controllers/**/*.rb # Roda's nested controllers require large blocks
    - spec/**/* # Minitest's nested test structure requires large blocks
    - Rakefile # Rake namespaces produce large blocks

# allow unsafe YAML loading in test code only
Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

Style/HashSyntax:
  Enabled: true
  Exclude:
    - Rakefile

Style/SymbolArray:
  Enabled: true
  Exclude:
    - Rakefile

Lint/ConstantDefinitionInBlock:
  Enabled: true
  Exclude:
    - Rakefile

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Lint/NonDeterministicRequireOrder:
  Enabled: true
  Exclude:
    - init.rb