---
development:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/dev.db
  REPOSTORE_PATH: app/infrastructure/git/repostore

test:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  REPOSTORE_PATH: app/infrastructure/git/repostore

app_test:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  REPOSTORE_PATH: app/infrastructure/git/repostore
  # Application
  APP_HOST: http://localhost:9000

production:
  # Infrastructure
  REPOSTORE_PATH: app/infrastructure/git/repostore