---
# Name the file secrets.yml

development:
  GITHUB_TOKEN: <personal access token for github api>
  REDISCLOUD_URL: <url assigned by Redis provider on Heroku>

test:
  GITHUB_TOKEN: <personal access token for github api>
  REDISCLOUD_URL: <url assigned by Redis provider on Heroku>

production:
  GITHUB_TOKEN: <personal access token for github api>
  REDISCLOUD_URL: <url assigned by Redis provider on Heroku>