---
# Name the file secrets.yml

development:
  GITHUB_TOKEN: <personal access token for github api>
  REDISCLOUD_URL: <url assigned by Redis provider on Heroku>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>

test:
  GITHUB_TOKEN: <personal access token for github api>
  REDISCLOUD_URL: <url assigned by Redis provider on Heroku>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>

production:
  GITHUB_TOKEN: <personal access token for github api>
  REDISCLOUD_URL: <url assigned by Redis provider on Heroku>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>